In [1]:
# Importing libraries 
import numpy as np 
import pandas as pd 

from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

from sklearn.model_selection import train_test_split

# reading the .csv file using pandas
df = pd.read_csv(r"C:\Users\AAKASH\Desktop\Project_ML\Flight_Delay_Prediction\Dataset\Processed_data1.csv") 

In [2]:
df.head(90)

year  month  day carrier origin dest  delayed
0   2013      1    1      UA    EWR  IAH        0
1   2013      1    1      UA    LGA  IAH        0
2   2013      1    1      AA    JFK  MIA        0
3   2013      1    1      B6    JFK  BQN        0
4   2013      1    1      DL    LGA  ATL        0
..   ...    ...  ...     ...    ...  ...      ...
85  2013      1    1      UA    EWR  MCO        1
86  2013      1    1      B6    JFK  SYR        0
87  2013      1    1      B6    JFK  SFO        0
88  2013      1    1      AA    LGA  ORD        0
89  2013      1    1      UA    EWR  IAH        0

[90 rows x 7 columns]

In [3]:
columns = ['carrier','dest', 'origin']
label = LabelEncoder()
for i in columns:
     df[i] = label.fit_transform(df[i])

In [4]:
df['carrier'].unique()

array([11,  1,  3,  4,  5,  9, 12, 14, 13,  7,  2,  0,  6,  8, 15, 10])

In [5]:
df['origin'].unique()

array([0, 2, 1])

In [6]:
df['dest'].unique()

array([ 43,  57,  12,   4,  68,  35,  42,  53,  70,  99,  49,  89,  30,
        11,  48,  60,  32,  82,  91,  73,  16,  23,  14,  29,  94,  61,
        92, 103,  58,  88,  81,  98,  95,  79,  24,  47,  21,  55,  74,
        83,  28,  22,  96,  64,  46,  54,  40,  10,   5,  13,  72,  97,
        33,   6,  78,  45,  85,  19,  41,  51,  27,   2,   7,  56,  59,
        37,  26,  15,  80,  38,  36,  52,  69,  84,  87,  71,  90,  67,
        25,  65,  93, 102,  77,  31,  75, 100,   9,  66,  18,  39,  17,
        62,  34,  76,   1,   8,   0,  44,  63,  86,  50,  20, 101,   3])

In [7]:
df.head(90)

year  month  day  carrier  origin  dest  delayed
0   2013      1    1       11       0    43        0
1   2013      1    1       11       2    43        0
2   2013      1    1        1       1    57        0
3   2013      1    1        3       1    12        0
4   2013      1    1        4       2     4        0
..   ...    ...  ...      ...     ...   ...      ...
85  2013      1    1       11       0    53        1
86  2013      1    1        3       1    98        0
87  2013      1    1        3       1    89        0
88  2013      1    1        1       2    68        0
89  2013      1    1       11       0    43        0

[90 rows x 7 columns]

In [8]:
X = df.iloc[:, 0:6].values # from column(years) to column(distance)
X[0:5]

array([[2013,    1,    1,   11,    0,   43],
       [2013,    1,    1,   11,    2,   43],
       [2013,    1,    1,    1,    1,   57],
       [2013,    1,    1,    3,    1,   12],
       [2013,    1,    1,    4,    2,    4]], dtype=int64)

In [9]:
y = df['delayed']
y.head().to_frame()

delayed
0        0
1        0
2        0
3        0
4        0

In [10]:
for i in range(0, 20):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=i)
    
    # creating random forest classifier
    clf = RandomForestClassifier(random_state=i)
    clf.fit(X_train, y_train)
    
    # determining the score
    train_score = clf.score(X_train, y_train)
    test_score = clf.score(X_test, y_test)
    print("Test: {}, Train: {} and Random State: {}".format(test_score, train_score, i))

Test: 0.8429683395041363, Train: 0.9113841040450655 and Random State: 0
Test: 0.846120947737576, Train: 0.9106427870261375 and Random State: 1
Test: 0.8441047447975855, Train: 0.9109197626156271 and Random State: 2
Test: 0.8419785671517773, Train: 0.9111885918642494 and Random State: 3
Test: 0.8449601036206117, Train: 0.9111885918642494 and Random State: 4
Test: 0.8445324242090986, Train: 0.9109523479790965 and Random State: 5
Test: 0.8460476312670308, Train: 0.9106631528783059 and Random State: 6
Test: 0.844874567738309, Train: 0.9110012260243006 and Random State: 7
Test: 0.8430049977394088, Train: 0.9113148601476931 and Random State: 8
Test: 0.8449112259735816, Train: 0.9110256650469025 and Random State: 9
Test: 0.8443246942092207, Train: 0.9107364699461119 and Random State: 10
Test: 0.8449723230323692, Train: 0.9110175187060352 and Random State: 11
Test: 0.8431882889157716, Train: 0.9111397138190453 and Random State: 12
Test: 0.8432371665628017, Train: 0.9110378845582036 and Random 

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=18)
clf = RandomForestClassifier(random_state=18)
clf.fit(X_train, y_train)

RandomForestClassifier(random_state=18)

In [12]:
print("Train set: ", clf.score(X_train, y_train))

Train set:  0.9112089577164177


In [13]:
print("Test set: ", clf.score(X_test, y_test))

Test set:  0.844116964209343


In [14]:
# predicting the trained Classifier to the test
yhat = clf.predict(X_test)

In [15]:
# Viewing the predicted probabilities of first 10 observations
yhat_prob = clf.predict_proba(X_test)[:10]

In [16]:
print(classification_report(y_test, yhat))

              precision    recall  f1-score   support

           0       0.88      0.94      0.91     71196
           1       0.32      0.18      0.23     10641

    accuracy                           0.84     81837
   macro avg       0.60      0.56      0.57     81837
weighted avg       0.81      0.84      0.82     81837

